### ISSUE TITLE
WARNING: Creating a duplicate database object for the same connection

### ISSUE THREAD

**Issue by nbulaj** [tobinbradley/dirt-simple-postgis-http-api#14]
Hi. I see next warning while using `dirt-simple-postgis-http-api`:

> WARNING: Creating a duplicate database object for the same connection.
>     at handler (/home/bulai/projects/dirt-simple-postgis-http-api/routes/mvt_v1.js:73:18)
>     at Object.internals.handler (/home/bulai/projects/dirt-simple-postgis-http-api/node_modules/hapi/lib/handler.js:96:36)
>     at request._protect.run (/home/bulai/projects/dirt-simple-postgis-http-api/node_modules/hapi/lib/handler.js:30:23)
>     at internals.Protect.run (/home/bulai/projects/dirt-simple-postgis-http-api/node_modules/hapi/lib/protect.js:64:5)
>     at exports.execute (/home/bulaj/projects/dirt-simple-postgis-http-api/node_modules/hapi/lib/handler.js:24:22)
>     at each (/home/bulai/projects/dirt-simple-postgis-http-api/node_modules/hapi/lib/request.js:383:16)

I took a look at the [routes/mvt_v1.js](https://github.com/tobinbradley/dirt-simple-postgis-http-api/blob/master/routes/mvt_v1.js#L73) and saw that it initialize a DB connection everytime handler called. I think it can be placed somewhere at the top to prevent memory leaks and in order to optimize the speed of the server.

**Comment by tobinbradley** [comment]
Yep. That's something I need to fix. 

It is where it is currently because it was previously using pg for database connections. It was a performance vs stability issue. Creating a single connection on app load reduces connection creation overhead and it makes the number of Postgres connections more predictable. 

On the other hand, if using a single pooled connection and it ever goes bad - database server restarted, session idle connection is terminated by the server, network blip, etc. - as far as I can tell, with pg, you're screwed.

But I switched it to pg-promise which uses lazy connections - only the actual query methods acquire and release the connection automatically. That should eliminate pg's dead connection issue, and it's why they recommend creating only one global/shared db object per connection (and give a warning if you don't).

It's on my todo list. :)

**Comment by tobinbradley** [comment]
And...I think it's done. The pgp connection is via a module in the config folder, which should make one shared pool for all the routes. I also updated all the project dependencies while I was at it.

**Comment by vitaly-t** [comment]
https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise

**Comment by tobinbradley** [comment]
Thanks @vitaly-t! I pretty much copied that example whole cloth - they link to that Stack Overflow solution in pg-promise's docs :).
