### ISSUE TITLE
which SRID should i upload the data with for the new MVT endpoint ?

### ISSUE THREAD

**Issue by mapsgeek** [tobinbradley/dirt-simple-postgis-http-api#17]
i upload the data into postgis with srid 4326 and it works fine with the old mvt endpoint, except for a warning about not following v2 specs but when it comes to the new endpoint the data renders at the very top of the map edge as attached
![image](https://user-images.githubusercontent.com/10188264/36287349-f2d9c67c-12bc-11e8-8ea3-ca81a837b0a4.png)

**Comment by tobinbradley** [comment]
Should work with any SRID, assuming your SRID is correctly specified in your geometry_columns view. 3857 is the fastest as there's no projection involved, but I've had it working fine with data in a state plane projection. Does it similarly break with other data, or just one specific layer?

**Comment by mapsgeek** [comment]
not stable at all with many data sources, tried with different SRIDs mainly 3857 and 4326, sometimes the projection renders right but with rendering errors while zooming into different levels, like random lines appear where shouldn't be. i'm trying to implement the stack in a project whether with the old endpoint or the new but i started to believe that generating mvt on the fly won't really work out to be stable for production! maybe i will use Geojson sources better or mapbox hosted.

**Comment by tobinbradley** [comment]
There is definitely something weird going on. It seems to be data dependent. I can replicate the problem with natural earth country polys layer small scale (1:110m) at some low zoom levels. When I try natural earth country polys large scale (1:10m), or natural earth rivers large scale, it works fine at all zoom levels (though slowly when zoomed way out). 

The SQL seems to be correct, otherwise it would never work. Best guess is it's some kind bug in the mvt tile conversion in postgis. Maybe it's hitting some upper tile limit for feature complexity? Beats me. When I wrote the service I tested with buildings and at that zoom level never had a problem. 

Wish I had a better answer for you. I'd only do dynamic MVT for layers that changed constantly and had to be as current as possible. Otherwise you're delivering slow tiles and crushing your CPU for no good reason.

**Comment by mapsgeek** [comment]
thanks tobin for your help so far, i always have this assumption that using MVT tiles will be faster and lighter than using plain geojson data, i don't know where this came from for real but i think i will end up using the geojson end point because my data is dynamic so going Tippecanoe and mbtiles won't work.
please if you have better options or suggestions for which better data sources to use with mapboxgl it would be more than appreciated.

**Comment by tobinbradley** [comment]
If your GeoJSON is small enough to make it over the wire, no reason not to use it. MVT speed is mostly due to size over the wire (though pbf being binary is a little faster to parse on the client). 

You might try [Tegola](https://github.com/terranodo/tegola). It's written in Go and is built strictly for serving MVT from PostGIS.
