### ISSUE TITLE
Log more specific database errors

### ISSUE THREAD

**Issue by rbrtmrtn** [tobinbradley/dirt-simple-postgis-http-api#53]
Hello again!

I am deploying Dirt to a PaaS ([Render](https://render.com/)) and overall it's pretty slick to be able to point it at this repo and deploy by setting some environment variables! Lots of time saved with this new config approach 🎉 

One thing I'm working through is that Dirt is having trouble connecting to my database and in order to dig in, I'm having to add some error logging to a forked copy and redeploy the app, which takes time. I've run into this before where Dirt will return a `500: Database connection error` and it's a little opaque to me what's going wrong.

So, this is a somewhat hazy ask to add a server-side `console.error` to spit out more details when there's a problem connecting to the database. I'd be happy to take a pass at a PR on this, if it sounds helpful. Also would love to know if there's a better debugging strategy I'm not thinking of!

**Comment by tobinbradley** [comment]
Let me take a look at that. It would probably be better to integrate that with fasify's logger than to console.xxx it. 

The reason why it only returns a vague 500 to the client is the actual db connection error message can leak info you probably want to keep under wraps - db server name, database name, db user name, etc. But it would be handy to log that on the server, 

I might make the `SERVER_LOGGER` a level rather than just on or off. Fastify's info logger is the default and it's noisy.

**Comment by rbrtmrtn** [comment]
This is awesome @tobinbradley! I set `POSTGRES_CONNECTION=foo` and I'm seeing the exact error message now. Love that the logging levels are configurable via env vars now, too. Thanks so much for the quick response on this!
